services:
  csboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION:-v1.10.0}

    container_name: csboard
    restart: unless-stopped

    ports:
      - "${PORT:-3000}:3000"

    environment:
      NODE_ENV: production
      PORT: 3000
      LOCAL_MAPS_DIR: /app/.local/maps

    volumes:
      - type: bind
        source: ./.local/maps
        target: /app/.local/maps
        read_only: true
