import { useRef, useState } from 'react';
import { localize } from '../i18n.js';
import { toolDisplay } from './toolLabels.js';
import { DEFAULT_COMPRESSION } from './contextCompression.js';

export default function AiSessionManager({ language, sessions, busy, selectSession, toolDefinitions, runWorkflow, onError }) {
  const text = (zh, en, ru) => localize(language, { zh, en, ru });
  const [tab, setTab] = useState('memory'); const [importing, setImporting] = useState(false);
  const fileRef = useRef(null); const busyRef = useRef(busy); busyRef.current = busy;
  const active = sessions.active;
  const [thresholdDraft, setThresholdDraft] = useState(null);
  const compression = active.compression || DEFAULT_COMPRESSION;
  const thresholdValue = thresholdDraft?.id === active.id ? thresholdDraft.value : String(compression.threshold); const blocked = busy || importing || !sessions.loaded;
  const updateStep = (id, patch) => sessions.patch(session => ({ ...session, workflow: session.workflow.map(step => step.id === id ? { ...step, ...patch } : step) }));
  const move = (index, direction) => sessions.patch(session => { const workflow = [...session.workflow]; [workflow[index], workflow[index + direction]] = [workflow[index + direction], workflow[index]]; return { ...session, workflow }; });
  return <section className="ai-session-manager">
    <div className="ai-session-toolbar"><select aria-label={text('切换会话', 'Switch session', 'Выбрать диалог')} disabled={blocked} value={active.id} onChange={event => selectSession(event.target.value)}>{sessions.sessions.map(session => <option key={session.id} value={session.id}>{session.title}</option>)}</select><button type="button" disabled={blocked} onClick={sessions.exportFile}>{text('导出', 'Export', 'Экспорт')}</button><button type="button" disabled={blocked} onClick={() => fileRef.current.click()}>{text('导入', 'Import', 'Импорт')}</button></div>
    <input type="file" accept="application/json,.json" hidden ref={fileRef} onChange={async event => { const file = event.target.files[0]; event.target.value = ''; if (!file) return; setImporting(true); try { if (busyRef.current) throw new Error('Stop execution before importing a session'); await sessions.importFile(file, toolDefinitions.map(tool => tool.function.name), () => !busyRef.current); } catch (error) { onError(error.message); } finally { setImporting(false); } }} />
    <details><summary>{text('会话记忆与工作流', 'Session memory and workflow', 'Память и процесс')}</summary>
      <fieldset disabled={blocked}>
        <label>{text('会话名称', 'Session name', 'Название')}<input maxLength={120} value={active.title} onChange={event => sessions.patch(session => ({ ...session, title: event.target.value }))} /></label>
        <div className="ai-session-tabs"><button type="button" aria-pressed={tab === 'memory'} onClick={() => setTab('memory')}>{text('记忆', 'Memory', 'Память')}</button><button type="button" aria-pressed={tab === 'workflow'} onClick={() => setTab('workflow')}>{text('工作流', 'Workflow', 'Процесс')}</button><button type="button" aria-pressed={tab === 'context'} onClick={() => setTab('context')}>{text('上下文', 'Context', 'Контекст')}</button></div>
        {tab === 'memory' && <><label className="ai-compression-enable"><input type="checkbox" checked={compression.enabled} onChange={event => sessions.patch(session => ({ ...session, compression: { ...compression, enabled: event.target.checked } }))} />{text('自动压缩上下文', 'Automatically compress context', 'Автоматически сжимать контекст')}</label>
          <label>{text('压缩阈值（文本字符，默认 60,000）', 'Compression threshold (text characters; default 60,000)', 'Порог сжатия (символы; по умолчанию 60 000)')}<input type="number" min={12000} max={240000} step={1000} disabled={blocked || !compression.enabled} value={thresholdValue} onChange={event => setThresholdDraft({ id: active.id, value: event.target.value })} onBlur={() => { const threshold = Number(thresholdValue); if (!Number.isInteger(threshold) || threshold < 12000 || threshold > 240000) { onError(text('阈值须为 12,000–240,000 的整数。', 'Threshold must be an integer between 12,000 and 240,000.', 'Порог должен быть целым числом от 12 000 до 240 000.')); setThresholdDraft(null); return; } sessions.patch(session => ({ ...session, compression: { ...compression, threshold } })); setThresholdDraft(null); }} /></label>
          <small>{text('达到阈值时额外调用模型生成摘要，保留当前请求和近期工具交换；原始会话不删除。阈值按文本估算，图片独立计量；当前状态无法压缩时可能仍超出阈值。', 'At the threshold, an extra model call summarizes older context while retaining the current request and recent tool exchanges. Originals remain. Images have a separate budget; essential state may exceed the threshold.', 'При достижении порога дополнительный запрос создаёт резюме. Текущий запрос, последние инструменты и оригиналы сохраняются. Изображения учитываются отдельно.')}</small>
          {active.compaction?.summary && <details><summary>{text('压缩摘要', 'Compression summary', 'Резюме сжатия')} · {active.compaction.count}</summary><pre>{active.compaction.summary}</pre><small>{active.compaction.updatedAt}</small></details>}
          <label>{text('长期记忆（可编辑）', 'Persistent memory (editable)', 'Постоянная память')}<textarea rows={5} maxLength={16000} value={active.memory} onChange={event => sessions.patch(session => ({ ...session, memory: event.target.value }))} placeholder={text('记录偏好、术语约定与已确认事实。助手也可保存明确的事实。', 'Preferences, terminology and confirmed facts. The assistant can also remember explicit facts.', 'Предпочтения, термины и подтверждённые факты.')} /></label><small>{text('对话长期保存在本地；每轮发送近期历史、记忆和当前上下文，更早消息可由助手检索。会话切换不会恢复或修改画布。', 'Chats persist locally. Requests include recent history, memory and current context; older messages are searchable. Switching sessions does not restore or edit the board.', 'Диалоги сохраняются локально. Модель получает память и текущий контекст; старые сообщения доступны для поиска. Выбор диалога не меняет доску.')}</small></>}
        {tab === 'context' && <><small>{text('保存最近 500 条变化，含手动及协作修改；不推断操作者。下次请求发送当前状态与近期变化，不自动调用模型。', 'Retains the latest 500 observations, including manual and collaborative changes; actor attribution is unknown. Sends current state and recent changes on the next request, without automatic model calls.', 'Сохраняются последние 500 наблюдений без определения автора. Контекст отправляется при следующем запросе.')}</small><pre>{JSON.stringify(active.snapshot, null, 2)}</pre>{active.events.slice(-12).reverse().map(event => <details key={event.id}><summary>{event.timestamp} · {event.type}</summary><pre>{JSON.stringify(event, null, 2)}</pre></details>)}</>}
        {tab === 'workflow' && <><small>{text('按顺序执行指令。每步可限制工具；不选工具只生成回复。失败、取消、等待输入或切换存档时停止后续步骤，不自动恢复。', 'Runs instructions in order. Select allowed tools for each step; none means reply only. Errors, cancellation, user input or archive changes stop later steps; no automatic resume.', 'Шаги выполняются по порядку. Без выбранных инструментов — только ответ. Ошибка, отмена или смена архива останавливает процесс.')}</small>
          {active.workflow.map((step, index) => <div className="ai-workflow-step" key={step.id}><div><b>{index + 1}</b><input aria-label={text('步骤名称', 'Step name', 'Название шага')} maxLength={120} value={step.name} onChange={event => updateStep(step.id, { name: event.target.value })} /><button type="button" disabled={blocked || index === 0} onClick={() => move(index, -1)}>↑</button><button type="button" disabled={blocked || index === active.workflow.length - 1} onClick={() => move(index, 1)}>↓</button><button type="button" onClick={() => sessions.patch(session => ({ ...session, workflow: session.workflow.filter(item => item.id !== step.id) }))}>{text('删除', 'Remove', 'Удалить')}</button></div><textarea rows={3} maxLength={6000} value={step.prompt} aria-label={text('步骤指令', 'Step instruction', 'Инструкция')} onChange={event => updateStep(step.id, { prompt: event.target.value })} /><details><summary>{text('允许工具', 'Allowed tools', 'Доступные инструменты')} · {step.tools.length}</summary><div className="ai-workflow-tools">{toolDefinitions.map(tool => <label key={tool.function.name} title={toolDisplay(tool.function.name, language).description}><input type="checkbox" checked={step.tools.includes(tool.function.name)} onChange={event => updateStep(step.id, { tools: event.target.checked ? [...step.tools, tool.function.name] : step.tools.filter(name => name !== tool.function.name) })} /><span>{toolDisplay(tool.function.name, language).label}</span><code className="ai-tool-id">{tool.function.name}</code></label>)}</div></details></div>)}
          <div className="ai-session-tabs"><button type="button" disabled={blocked || active.workflow.length >= 24} onClick={() => sessions.patch(session => ({ ...session, workflow: [...session.workflow, { id: crypto.randomUUID(), name: '', prompt: '', tools: ['get_board_state', 'get_session_memory'] }] }))}>{text('添加步骤', 'Add step', 'Добавить шаг')}</button><button type="button" disabled={blocked || !active.workflow.length || active.workflow.some(step => !step.prompt.trim()) || !active.snapshot?.enabled} onClick={runWorkflow}>{text('执行工作流', 'Run workflow', 'Запустить')}</button></div>
        </>}
        <button type="button" className="ai-session-delete" onClick={() => { if (window.confirm(text('删除当前会话及其记忆、工作流？画布不受影响。', 'Delete this session, memory and workflow? The board is unaffected.', 'Удалить диалог, память и процесс? Доска не изменится.'))) sessions.remove(); }}>{text('删除此会话', 'Delete session', 'Удалить диалог')}</button>
      </fieldset>
    </details>
    {sessions.storageError && <p className="ai-error" role="alert">{text('会话保存失败：', 'Session storage failed: ', 'Ошибка сохранения: ')}{sessions.storageError}</p>}
  </section>;
}
